### ISSUE TITLE
Installation fails at Jupyterlab build

### ISSUE THREAD

**Issue by neubig** [mkery/Verdant#42]
Hello, thanks for the interesting package!

I was looking to try it out, but am having trouble with install, apparently due to versioning issues. Any chance you could provide assistance? Here are the full commands to reproduce from a clean conda environment:

    conda create --name=verdant python=3 jupyterlab
    conda activate verdant
    git clone https://github.com/mkery/Verdant.git
    cd Verdant/
    pip install lilgit-parser
    jupyter serverextension enable --py lilgit_parser
    jupyter serverextension list
    npm install
    npm run build
    jupyter labextension link .

At this point it dies with the following error:

    $ jupyter labextension link .
    An error occured.
    ValueError: 
    "Verdant@0.1.0" is not compatible with the current JupyterLab
    Conflicting Dependencies:
    JupyterLab              Extension      Package
    >=1.1.3 <1.2.0          >=0.19.1 <0.20.0@jupyterlab/application
    >=1.1.3 <1.2.0          >=0.19.1 <0.20.0@jupyterlab/apputils
    >=3.1.0 <3.2.0          >=2.2.1 <3.0.0 @jupyterlab/coreutils
    >=1.1.3 <1.2.0          >=0.19.1 <0.20.0@jupyterlab/docmanager
    >=1.1.3 <1.2.0          >=0.19.1 <0.20.0@jupyterlab/notebook
    >=1.1.3 <1.2.0          >=0.19.1 <0.20.0@jupyterlab/rendermime
    >=4.1.1 <4.2.0          >=3.2.1 <4.0.0 @jupyterlab/services
    See the log file for details:  /var/folders/n9/8zbz_v_14ys5cdmn0vy0b9_w0000gn/T/jupyterlab-debug-qcke3yko.log

 Looking in `packages.json`, it seems that a specific version for JupyterLab is specified, but I wasn't able to figure out how to install the specific version (the version numbers are different for different parts of the package, and it's not even possible to install 0.19.1 from pip at the moment). Would it be possible to get some directions about what to do to get this working? Thanks!

**Comment by mkery** [comment]
Thanks! Just pushed an update [2947b03](https://github.com/mkery/Verdant/commit/2947b0375fb0d3fcd56941e08fc4f0299292314f)  which should fix this!

**Comment by neubig** [comment]
Thanks a bunch! I was able to install and run no problem with the newest version.
