### ISSUE TITLE
yarn start fails with conflicting dependencies

### ISSUE THREAD

**Issue by d0rg0ld** [mkery/Verdant#74]
Hello, I would like to try this promising extension, but its installation fails with conflicting dependencies, such as here under Ubuntu 18

yarn start
yarn run v1.22.5
$ jupyter labextension install . && jupyter lab .
An error occured.
ValueError:
"verdant-history@1.0.1" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=3.0.2 <3.1.0          >=2.1.0 <3.0.0   @jupyterlab/application
>=3.0.2 <3.1.0          >=2.1.0 <3.0.0   @jupyterlab/apputils
>=3.0.2 <3.1.0          >=2.1.0 <3.0.0   @jupyterlab/codemirror
>=5.0.1 <5.1.0          >=4.1.0 <5.0.0   @jupyterlab/coreutils
>=3.0.2 <3.1.0          >=2.1.0 <3.0.0   @jupyterlab/docmanager
>=3.0.2 <3.1.0          >=2.1.0 <2.2.0   @jupyterlab/notebook
>=3.0.2 <3.1.0          >=2.1.0 <3.0.0   @jupyterlab/rendermime
>=6.0.2 <6.1.0          >=5.1.0 <6.0.0   @jupyterlab/services
>=17.0.1 <18.0.0        >=16.9.0 <16.10.0react
>=17.0.1 <18.0.0        >=16.9.0 <16.10.0react-dom
See the log file for details:  /tmp/jupyterlab-debug-3g59dvsp.log
error Command failed with exit code 1.

I tried it on Mac as well, same problem. Do you probably have a solution or could help me with installing the right versions? Thanks a lot, Doron

**Comment by mkery** [comment]
On it. It looks like we need some updates to work with the latest release of JupyterLab. Will get this fixed today, thanks!

**Comment by d0rg0ld** [comment]
Thank you for this really quick reply!

**Comment by mkery** [comment]
Just updated with a fix and published to npm the fixed version as well.

No one but me is currently using this tool, lol, so let me know if you run into any more install issues thanks! :)

**Comment by d0rg0ld** [comment]
Hi, Thanks a lot for the quick fix, I managed to start the extension and will explore today. Will notify you of any issues encountered ... Best, Doron
