### ISSUE TITLE
Update Readme to list Jupyterlab v3

### ISSUE THREAD

**Issue by nikmart** [mkery/Verdant#78]
JupyterLab v3 seems to be required to run Verdant. It might be nice to update `README.md` and link to how to install JupyterLab v3: [https://blog.jupyter.org/jupyterlab-3-0-is-out-4f58385e25bb](https://blog.jupyter.org/jupyterlab-3-0-is-out-4f58385e25bb)

**Comment by mkery** [comment]
Thanks! I've added the details on how to install (or update to) JupyterLab 3.0 in the `README.md` ca4439e4a1de5f4a46c579710399f1119afe4fc3
